# Generated by Django 5.0.7 on 2024-08-20 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_note_text_alter_note_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['date']},
        ),
    ]
